### ISSUE TITLE
Validation Question

### ISSUE THREAD

**Issue by omolchanov** [2amigos/yii2-date-time-picker-widget#11]
Hi guys,

It would be great if you can help me a bit with this question - http://www.yiiframework.com/forum/index.php/topic/69887-validation-for-datetime-widget/ 

Many thanks in advance!

**Comment by tonydspaniard** [comment]
http://www.yiiframework.com/forum/index.php/topic/69887-validation-for-datetime-widget/page__view__findpost__p__310725
