### ISSUE TITLE
Header when Time Picking only is broken

### ISSUE THREAD

**Issue by newscloud** [2amigos/yii2-date-time-picker-widget#16]
see https://github.com/smalot/bootstrap-datetimepicker/issues/569#issuecomment-267224532

there's a fix coming available

**Comment by newscloud** [comment]
Please update to "bower-asset/smalot-bootstrap-datetimepicker": "2.4.2" to fix this.

**Comment by tonydspaniard** [comment]
https://github.com/2amigos/yii2-date-time-picker-widget/blob/master/composer.json#L31
