### ISSUE TITLE
Auto-select language

### ISSUE THREAD

**Issue by marcovtwout** [2amigos/yii2-date-time-picker-widget#6]
When I create the widget without using options, Yii::$app->language is not used. Could you adjust this component to use the app language by default, like https://github.com/kartik-v/yii2-widget-datetimepicker?

**Comment by tonydspaniard** [comment]
@marcovtwout don't you think is better to allow the user to have that flexibility? I tend to dislike widgets that do far too much magic. The widget assumes that your  "default" language setting is "en" as the widget itself.

**Comment by marcovtwout** [comment]
It's a good question. I think any component should be flexible but should also provide good defaults when you create it with zero options. When in doubt about good default values, I look at what the framework components do.

Yii 2's DatePicker also uses it, see: http://www.yiiframework.com/doc-2.0/yii-jui-datepicker.html#$language-detail
By my reasoning, using the application language is a good default, since other interface elements like labels are also localized.

**Comment by tonydspaniard** [comment]
@marcovtwout what happens if your language set is not compatible or not supported by the library itself?

**Comment by marcovtwout** [comment]
Take a look at https://github.com/yiisoft/yii2-jui/blob/master/DatePicker.php
I guess it should default to english.

**Comment by tonydspaniard** [comment]
@marcovtwout will do that. Thanks.
