### ISSUE TITLE
problem in installing widget 

### ISSUE THREAD

**Issue by M-Fares** [2amigos/yii2-date-time-picker-widget#9]
using the following command I get the following result:
sudo composer require 2amigos/yii2-date-time-picker-widget:~1.0

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-date-time-picker-widget 1.0.x-dev requires bower-asset/smalot-bootstrap-datetimepicker 2.3.1 -> no matching package found.
    - 2amigos/yii2-date-time-picker-widget 1.0.2 requires bower-asset/smalot-bootstrap-datetimepicker 2.3.1 -> no matching package found.
    - 2amigos/yii2-date-time-picker-widget 1.0.1 requires bower-asset/smalot-bootstrap-datetimepicker 2.3.1 -> no matching package found.
    - 2amigos/yii2-date-time-picker-widget 1.0.0 requires bower-asset/smalot-bootstrap-datetimepicker 2.3.1 -> no matching package found.
    - Installation request for 2amigos/yii2-date-time-picker-widget ~1.0 -> satisfiable by 2amigos/yii2-date-time-picker-widget[1.0.0, 1.0.1, 1.0.2, 1.0.x-dev].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by blonder413** [comment]
I have the same problem

**Comment by koxu1996** [comment]
I can not install this widget too.

**Comment by gohilronak** [comment]
As https://github.com/smalot/bootstrap-datetimepicker is not registered in https://packagist.org/, it is showing this error.
We can do following:

1. Install smalot-bootstrap-datetimepicker#2.3.1 using following command
       `bower install smalot-bootstrap-datetimepicker#2.3.1`
    This will copy required files in `\vendor\bower\smalot-bootstrap-datetimepicker` directory.

2. Clone https://github.com/2amigos/yii2-date-time-picker-widget.git 

3. Remove `"bower-asset/smalot-bootstrap-datetimepicker": "2.3.1"` from cloned project's composer.json.
It should look like this after removing
    ```
    "require": {
        "yiisoft/yii2": "~2.0",
        "yiisoft/yii2-bootstrap": "~2.0.0"
    },
    ```

4. Commit changes
    ```
    git add .
    git commit -m "remove dependency."
    ```

5. Update yii2's composer.json to following: (Please change `url` according to path where you have cloned repo.)
    ```
    "repositories": [
        {
            "type":"vcs",
            "url":"file://D:\\programs\\xampp\\htdocs\\packages\\yii2-date-time-picker-widget-master"
        }
    ],
    "require": {
        ...
        "2amigos/yii2-date-time-picker-widget": "dev-master"
    },
    ```

6. run `composer update --prefer-source`

Now datetimepicker widget is installed.

**Comment by tonydspaniard** [comment]
This issue is quite old (sorry for being unresponsive). I am going to close it as we have already solved what was the subject of it.

**Comment by ShokhrukhMukhtarov** [comment]
in composer.json write : 
  "minimum-stability": "dev",
    "prefer-stable": true,

and in CMD 
composer require 2amigos/yii2-date-picker-widget:"*"
